[package]
name = "nucleo-u5a5zj-bsp"
description = "A small BSP for the NUCLEO-U5A5ZJ-Q board"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m-semihosting.workspace = true
cortex-m.workspace = true
rand.workspace = true
stm32u5-tiny-hal.workspace = true
stm32u5.workspace = true

[lints.clippy]
missing_safety_doc = "deny"
undocumented_unsafe_blocks = "deny"

[lints.rust]
missing_docs = "deny"
unsafe_op_in_unsafe_fn = "deny"
unsafe_attr_outside_unsafe = "deny"
unused_unsafe = "deny"
