[package]
authors = ["Ferrous Systems"]
edition = "2021"
license = "MIT OR Apache-2.0"
name = "usb"
version = "0.0.0"
description = "Library for parsing USB requests"

[dependencies]
defmt = "1"
defmt-rtt = "1.1"
