[package]
name = "stm32u5-tiny-hal"
description = "A small HAL for STM32U5 series MCUs"
version = "0.1.0"
edition = "2024"

[dependencies]
stm32u5.workspace = true
cortex-m.workspace = true
cortex-m-semihosting.workspace = true

[lints.clippy]
missing_safety_doc = "deny"
undocumented_unsafe_blocks = "deny"

[lints.rust]
missing_docs = "deny"
unsafe_op_in_unsafe_fn = "deny"
unsafe_attr_outside_unsafe = "deny"
unused_unsafe = "deny"
