[package]
name = "standalone-app"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m-rt.workspace = true
cortex-m.workspace = true
critical-section.workspace = true
defmt-rtt.workspace = true
defmt.workspace = true
green-yellow-solution.workspace = true
heapless.workspace = true
nucleo-u5a5zj-bsp.workspace = true
rand.workspace = true
rtic.workspace = true
rtic-monotonics.workspace = true

[lints.clippy]
missing_safety_doc = "deny"
undocumented_unsafe_blocks = "deny"

[lints.rust]
missing_docs = "deny"
unsafe_op_in_unsafe_fn = "deny"
unsafe_attr_outside_unsafe = "deny"
unused_unsafe = "deny"
