[package]
name = "secure-loader"
description = "A Secure State binary running from Flash Bank 1 and SRAM1"
version = "0.1.0"
edition = "2024"

[dependencies]
cortex-m-rt.workspace = true
nucleo-u5a5zj-bsp.workspace = true
cortex-m-semihosting.workspace = true
cortex-m.workspace = true
critical-section.workspace = true

[lints.clippy]
missing_safety_doc = "deny"
undocumented_unsafe_blocks = "deny"

[lints.rust]
missing_docs = "deny"
unsafe_op_in_unsafe_fn = "deny"
unsafe_attr_outside_unsafe = "deny"
unused_unsafe = "deny"
